-- SHENGDA: импорт 133 товаров с фотографиями
DELETE FROM products;

INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25056','sofas','','Диван YSF25056 (Модульный диван (левая 2-местная с подло)','YSF25056','Модульный диван (левая 2-местная с подлокотником + правая 2-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H946.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','252*103*64 см','H946','','',1,'hotel,apartment','assets/uploads/YSF25056.png',1,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25056-sec1','sofas','','Левая 2-местная секция с подлокотником (к дивану YSF25056)','YSF25056-SEC','Левая 2-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','126*103*64 см','','','',1,'hotel,apartment','assets/uploads/YSF25056.png',2,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25056-sec2','sofas','','Правая 2-местная секция с подлокотником (к дивану YSF25056)','YSF25056-SEC','Правая 2-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','126*103*64 см','','','',1,'hotel,apartment','assets/uploads/YSF25056.png',3,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25113','sofas','','Диван YSF25113 (Компрессионный диван)','YSF25113','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','312*105*80 см','','','(1270*37*37)*2/1220*310*310',1,'hotel,apartment','assets/uploads/YSF25113.png',4,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25118','sofas','','Диван YSF25118 (Компрессионный диван)','YSF25118','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','196*100*58 см','','','116*38*38',1,'hotel,apartment','assets/uploads/YSF25118.png',5,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25003k83-sec0','sofas','','Модульный диван (левая 3-местная секция + правый шезлонг) (к дивану YSF25003（K83）)','YSF25003（K83）-SEC','Модульный диван (левая 3-местная секция + правый шезлонг). Стандартная комплектация. Ткань/обивка: LVZ52-03.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','2760*1730*580 см','LVZ52-03','','40*43*110/37*38*110',1,'hotel,apartment','assets/uploads/YSF25003_K83.png',6,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25003k83-sec1','sofas','','Левая 3-местная секция (к дивану YSF25003（K83）)','YSF25003（K83）-SEC','Левая 3-местная секция. ','Высокоэластичный поролон, качественная обивка','1730*1060*580 см','','','40*43*110',1,'hotel,apartment','assets/uploads/YSF25003_K83.png',7,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25003k83-sec2','sofas','','Правый шезлонг (рекамье) (к дивану YSF25003（K83）)','YSF25003（K83）-SEC','Правый шезлонг (рекамье). ','Высокоэластичный поролон, качественная обивка','1730*1030*580 см','','','37*38*110',1,'hotel,apartment','assets/uploads/YSF25003_K83.png',8,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('accessory-pillow-8','sofas','','Декоративная подушка','YSF25003（K83）-P','Декоративная подушка. Декоративная подушка в комплекте к дивану YSF25003（K83）.','LVZ52-03','','LVZ52-03','','',0,'','assets/uploads/YSF25003_K83.png',9,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('accessory-pillow-9','sofas','','Поясничная подушка','YSF25003（K83）-P','Поясничная подушка. Декоративная подушка в комплекте к дивану YSF25003（K83）.','LVZ52-03','','LVZ52-03','','',0,'','assets/uploads/YSF25003_K83.png',10,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25004k85','sofas','','Диван YSF25004（K85） (Четырёхместный диван)','YSF25004（K85）','Четырёхместный диван. Стандартная комплектация. Ткань/обивка: Вельвет.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя
+ вельветовая ткань','3070*1040*730 см','Вельвет','','(35*35*108）*2+（30*30*88）',1,'hotel,apartment','assets/uploads/YSF25004_K85.png',11,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25006','sofas','','Диван YSF25006','YSF25006','Модель YSF25006. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25006.png',12,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25007','sofas','','Диван YSF25007','YSF25007','Модель YSF25007. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25007.png',13,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25008k91','sofas','','Диван YSF25008（K91） (Двухместный компрессионный диван)','YSF25008（K91）','Двухместный компрессионный диван. Стандартная комплектация. Ткань/обивка: «Гэдяо-8».','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя
+ вельветовая ткань','2060*1040*700 см','«Гэдяо-8»','','110*75*39',1,'hotel,apartment','assets/uploads/YSF25008_K91.png',14,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25025k118','sofas','','Диван YSF25025（K118） (Компрессионный модульный диван (левая 1-)','YSF25025（K118）','Компрессионный модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: S639-34.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','304*102*73 см','S639-34','','(33*33*117）*2+（31*31*87）',1,'hotel,apartment','assets/uploads/YSF25025_K118.png',15,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25025k118-sec1','sofas','','Левая 1-местная секция с подлокотником (к дивану YSF25025（K118）)','YSF25025（K118）-SEC','Левая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','111*102*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25025_K118.png',16,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25025k118-sec2','sofas','','1-местная секция без подлокотников (к дивану YSF25025（K118）)','YSF25025（K118）-SEC','1-местная секция без подлокотников. ','Высокоэластичный поролон, качественная обивка','82*102*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25025_K118.png',17,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25025k118-sec3','sofas','','Правая 1-местная секция с подлокотником (к дивану YSF25025（K118）)','YSF25025（K118）-SEC','Правая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','111*102*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25025_K118.png',18,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25042','sofas','','Диван YSF25042 (Модульный диван (левая 1-местная с подло)','YSF25042','Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: CKS063-12.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань премиум-класса','276*112*71 см','CKS063-12','','28*28*110/3',1,'hotel,apartment','assets/uploads/YSF25042.png',19,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25042-sec1','sofas','','Левая 1-местная секция с подлокотником (к дивану YSF25042)','YSF25042-SEC','Левая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','92*112*71 см','','','28*28*110',1,'hotel,apartment','assets/uploads/YSF25042.png',20,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25042-sec2','sofas','','1-местная секция без подлокотников (к дивану YSF25042)','YSF25042-SEC','1-местная секция без подлокотников. ','Высокоэластичный поролон, качественная обивка','92*112*71 см','','','28*28*110',1,'hotel,apartment','assets/uploads/YSF25042.png',21,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25042-sec3','sofas','','Правая 1-местная секция с подлокотником (к дивану YSF25042)','YSF25042-SEC','Правая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','92*112*71 см','','','28*28*110',1,'hotel,apartment','assets/uploads/YSF25042.png',22,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25050','sofas','','Диван YSF25050 (Модульный диван (левая 1-местная с подло)','YSF25050','Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H939+H940+H941.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','281*94*64 см','H939+H940+H941','','',1,'hotel,apartment','assets/uploads/YSF25050.png',23,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25050-sec1','sofas','','Левая 1-местная секция с подлокотником (к дивану YSF25050)','YSF25050-SEC','Левая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','95*94*64 см','','','',1,'hotel,apartment','assets/uploads/YSF25050.png',24,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25050-sec2','sofas','','1-местная секция без подлокотников (к дивану YSF25050)','YSF25050-SEC','1-местная секция без подлокотников. ','Высокоэластичный поролон, качественная обивка','91*94*64 см','','','',1,'hotel,apartment','assets/uploads/YSF25050.png',25,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25050-sec3','sofas','','Правая 1-местная секция с подлокотником (к дивану YSF25050)','YSF25050-SEC','Правая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','95*94*64 см','','','',1,'hotel,apartment','assets/uploads/YSF25050.png',26,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25052','sofas','','Диван YSF25052 (Модульный диван (левая 1-местная с подло)','YSF25052','Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H935+H936.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','273*91*65 см','H935+H936','','',1,'hotel,apartment','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',27,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25052-sec1','sofas','','Левая 1-местная секция с подлокотником (к дивану YSF25052)','YSF25052-SEC','Левая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','91*91*65 см','','','',1,'hotel,apartment','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',28,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25052-sec2','sofas','','1-местная секция без подлокотников (к дивану YSF25052)','YSF25052-SEC','1-местная секция без подлокотников. ','Высокоэластичный поролон, качественная обивка','91*91*65 см','','','',1,'hotel,apartment','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',29,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25052-sec3','sofas','','Правая 1-местная секция с подлокотником (к дивану YSF25052)','YSF25052-SEC','Правая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','91*91*65 см','','','',1,'hotel,apartment','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',30,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('accessory-pillow-30','sofas','','Декоративная подушка 1','YSF25052-P','Декоративная подушка 1. Декоративная подушка в комплекте к дивану YSF25052.','H935','','H935','','',0,'','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',31,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('accessory-pillow-31','sofas','','Декоративная подушка 2','YSF25052-P','Декоративная подушка 2. Декоративная подушка в комплекте к дивану YSF25052.','H936','','H936','','',0,'','assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',32,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25053-sec0','sofas','','Модульный диван (левая 1-местная с подлокотником + пуф/подст (к дивану YSF25053)','YSF25053-SEC','Модульный диван (левая 1-местная с подлокотником + пуф/подставка для ног + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H937+H938.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','276*92*73 см','H937+H938','','',1,'hotel,apartment','assets/uploads/YSF25053.png',33,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25053-sec1','sofas','','Левая 1-местная секция с подлокотником (к дивану YSF25053)','YSF25053-SEC','Левая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','92*92*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25053.png',34,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25053-sec2','sofas','','Пуф / подставка для ног (к дивану YSF25053)','YSF25053-SEC','Пуф / подставка для ног. ','Высокоэластичный поролон, качественная обивка','92**92*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25053.png',35,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25053-sec3','sofas','','Правая 1-местная секция с подлокотником (к дивану YSF25053)','YSF25053-SEC','Правая 1-местная секция с подлокотником. ','Высокоэластичный поролон, качественная обивка','92*92*73 см','','','',1,'hotel,apartment','assets/uploads/YSF25053.png',36,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('accessory-pillow-36','sofas','','Декоративная подушка','YSF25053-P','Декоративная подушка. Декоративная подушка в комплекте к дивану YSF25053.','H938','','H938','','',0,'','assets/uploads/YSF25053.png',37,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25011','sofas','','Диван YSF25011','YSF25011','Модель YSF25011. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25011.png',38,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25016k106','sofas','','Диван YSF25016（K106） (Компрессионный диван)','YSF25016（K106）','Компрессионный диван. Стандартная комплектация. Ткань/обивка: MA-05.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','102*80*62 см','MA-05','','90*28*28',1,'hotel,apartment','assets/uploads/YSF25016_K106.png',39,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25021k113','sofas','','Диван YSF25021（K113） (Компрессионный диван)','YSF25021（K113）','Компрессионный диван. Стандартная комплектация. Ткань/обивка: 639-12 (оранжевый) / 639-23 (синий).','Специальный высокоэластичный компрессионный поролон
+ шенилловая ткань','100*83*77 см','639-12 (оранжевый) / 639-23 (синий)','','28*28*88',1,'hotel,apartment','assets/uploads/YSF25021_K113.png',40,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25033','sofas','','Диван YSF25033 (Компрессионный диван)','YSF25033','Компрессионный диван. Стандартная комплектация. Ткань/обивка: H932.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','84*104*84 см','H932','','',1,'hotel,apartment','assets/uploads/YSF25033.png',41,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25048','sofas','','Диван YSF25048 (Компрессионный диван)','YSF25048','Компрессионный диван. Стандартная комплектация. Ткань/обивка: H933.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','95*108*68 см','H933','','',1,'hotel,apartment','assets/uploads/YSF25048.png',42,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25057','sofas','','Диван YSF25057 (Одноместный компрессионный диван)','YSF25057','Одноместный компрессионный диван. Стандартная комплектация. Ткань/обивка: H942.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','101*101*82 см','H942','','',1,'hotel,apartment','assets/uploads/YSF25057.png',43,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25060','sofas','','Диван YSF25060 (Компрессионный диван, 1-местный)','YSF25060','Компрессионный диван, 1-местный. Стандартная комплектация. Ткань/обивка: 651-7.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','110*106*66 см','651-7','','',1,'hotel,apartment','assets/uploads/YSF25060.png',44,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25061','sofas','','Диван YSF25061 (Компрессионный диван)','YSF25061','Компрессионный диван. Стандартная комплектация. Ткань/обивка: Синий.','Качественная ткань + высокоэластичный поролон + девятиканальное волокно','98*90*75 см','Синий','','96*35*35',1,'hotel,apartment','',45,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25101','sofas','','Диван YSF25101','YSF25101','Модель YSF25101. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25101.png',46,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25106','sofas','','Диван YSF25106','YSF25106','Модель YSF25106. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25106.png',47,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25107','sofas','','Диван YSF25107 (Компрессионный диван)','YSF25107','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань','100*83*75 см','','','32*32*92',1,'hotel,apartment','assets/uploads/YSF25107.png',48,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25119','sofas','','Диван YSF25119 (Компрессионный диван)','YSF25119','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»','166*97*76 см','','','120*39*39',1,'hotel,apartment','assets/uploads/YSF25119.png',49,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25120','sofas','','Диван YSF25120 (Компрессионный диван)','YSF25120','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + эластичная ткань','90*85*67 см','','','93*29*29',1,'hotel,apartment','assets/uploads/YSF25120.png',50,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25121','sofas','','Диван YSF25121 (Компрессионный диван)','YSF25121','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + эластичная ткань','85*73*71 см','','','81*27*27',1,'hotel,apartment','assets/uploads/YSF25121.png',51,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25123','sofas','','Диван YSF25123 (Компрессионный диван)','YSF25123','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань','100*100*77 см','','','81*27*27',1,'hotel,apartment','assets/uploads/YSF25123.png',52,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25124','sofas','','Диван YSF25124','YSF25124','Модель YSF25124. Подробные характеристики по запросу.','Высокоэластичный поролон, качественная обивочная ткань','','','','',1,'hotel,apartment','assets/uploads/YSF25124.png',53,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25005k88','sofas','','Диван YSF25005（K88） (Компрессионный диван)','YSF25005（K88）','Компрессионный диван. Стандартная комплектация. ','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань','80*80*70 см','','','87*27*27',1,'hotel,apartment','assets/uploads/YSF25005_K88.png',54,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25009k92','sofas','','Диван YSF25009（K92） (Одноместный диван)','YSF25009（K92）','Одноместный диван. Стандартная комплектация. Ткань/обивка: Вельвет.','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань','900*900*730 см','Вельвет','','109*32*32',1,'hotel,apartment','assets/uploads/YSF25009_K92.png',55,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofa-ysf25010k93','sofas','','Диван YSF25010（K93） (Одноместный диван)','YSF25010（K93）','Одноместный диван. Стандартная комплектация. Ткань/обивка: Ткань «тедди».','Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «овчина»','750*930*770 см','Ткань «тедди»','','82*31*31',1,'hotel,apartment','assets/uploads/YSF25010_K93.png',56,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2509-120200','beds','','Кровать YSC2509 (120×200)','YSC2509-120×200','Мягкая кровать YSC2509. Спальное место: 120×200 см. Обивка: Jie''en: SWR569C-1.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','233*165*101 см','Jie''en: SWR569C-1','','',1,'hotel,apartment','assets/uploads/YSC2509.png',57,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2509-150200','beds','','Кровать YSC2509 (150×200)','YSC2509-150×200','Мягкая кровать YSC2509. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','233*195*101 см','','','',1,'hotel,apartment','assets/uploads/YSC2509.png',58,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2509-180200','beds','','Кровать YSC2509 (180×200)','YSC2509-180×200','Мягкая кровать YSC2509. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','233*225*101 см','','','',1,'hotel,apartment','assets/uploads/YSC2509.png',59,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2501-120200','beds','','Кровать YSC2501 (120×200)','YSC2501-120×200','Мягкая кровать YSC2501. Спальное место: 120×200 см. Обивка: Qifei: QF0519-7.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*154*100 см','Qifei: QF0519-7','','',1,'hotel,apartment','assets/uploads/YSC2501.png',60,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2501-150200','beds','','Кровать YSC2501 (150×200)','YSC2501-150×200','Мягкая кровать YSC2501. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*184*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2501.png',61,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2501-180200','beds','','Кровать YSC2501 (180×200)','YSC2501-180×200','Мягкая кровать YSC2501. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*214*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2501.png',62,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2502-120200','beds','','Кровать YSC2502 (120×200)','YSC2502-120×200','Мягкая кровать YSC2502. Спальное место: 120×200 см. Обивка: Qifei: QF0519-13 + Luoweizan LVZ2005-02.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*154*100 см','Qifei: QF0519-13 + Luoweizan LVZ2005-02','','',1,'hotel,apartment','assets/uploads/YSC2502.png',63,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2502-150200','beds','','Кровать YSC2502 (150×200)','YSC2502-150×200','Мягкая кровать YSC2502. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*184*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2502.png',64,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2502-180200','beds','','Кровать YSC2502 (180×200)','YSC2502-180×200','Мягкая кровать YSC2502. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','237*214*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2502.png',65,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2503-120200','beds','','Кровать YSC2503 (120×200)','YSC2503-120×200','Мягкая кровать YSC2503. Спальное место: 120×200 см. Обивка: Qifei: QF0519-9.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','241*155*100 см','Qifei: QF0519-9','','',1,'hotel,apartment','assets/uploads/YSC2503.png',66,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2503-150200','beds','','Кровать YSC2503 (150×200)','YSC2503-150×200','Мягкая кровать YSC2503. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','241*185*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2503.png',67,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2503-180200','beds','','Кровать YSC2503 (180×200)','YSC2503-180×200','Мягкая кровать YSC2503. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','241*215*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2503.png',68,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2505-120200','beds','','Кровать YSC2505 (120×200)','YSC2505-120×200','Мягкая кровать YSC2505. Спальное место: 120×200 см. Обивка: Qifei: QF0519-3.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','242*155*107 см','Qifei: QF0519-3','','',1,'hotel,apartment','assets/uploads/YSC2505.png',69,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2505-150200','beds','','Кровать YSC2505 (150×200)','YSC2505-150×200','Мягкая кровать YSC2505. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','242*185*107 см','','','',1,'hotel,apartment','assets/uploads/YSC2505.png',70,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2505-180200','beds','','Кровать YSC2505 (180×200)','YSC2505-180×200','Мягкая кровать YSC2505. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','242*215*107 см','','','',1,'hotel,apartment','assets/uploads/YSC2505.png',71,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2506-120200','beds','','Кровать YSC2506 (120×200)','YSC2506-120×200','Мягкая кровать YSC2506. Спальное место: 120×200 см. Обивка: Qifei: QF0519-17.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','235*154*97 см','Qifei: QF0519-17','','',1,'hotel,apartment','assets/uploads/YSC2506.png',72,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2506-150200','beds','','Кровать YSC2506 (150×200)','YSC2506-150×200','Мягкая кровать YSC2506. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','235*184*97 см','','','',1,'hotel,apartment','assets/uploads/YSC2506.png',73,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2506-180200','beds','','Кровать YSC2506 (180×200)','YSC2506-180×200','Мягкая кровать YSC2506. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','235*214*97 см','','','',1,'hotel,apartment','assets/uploads/YSC2506.png',74,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2507-120200','beds','','Кровать YSC2507 (120×200)','YSC2507-120×200','Мягкая кровать YSC2507. Спальное место: 120×200 см. Обивка: Qifei: QF0519-16.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','240*154*97 см','Qifei: QF0519-16','','',1,'hotel,apartment','assets/uploads/YSC2507.png',75,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2507-150200','beds','','Кровать YSC2507 (150×200)','YSC2507-150×200','Мягкая кровать YSC2507. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','240*184*97 см','','','',1,'hotel,apartment','assets/uploads/YSC2507.png',76,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2507-180200','beds','','Кровать YSC2507 (180×200)','YSC2507-180×200','Мягкая кровать YSC2507. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','240*214*97 см','','','',1,'hotel,apartment','assets/uploads/YSC2507.png',77,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2508-120200','beds','','Кровать YSC2508 (120×200)','YSC2508-120×200','Мягкая кровать YSC2508. Спальное место: 120×200 см. Обивка: Qifei: QF0519-19.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','232*154*100 см','Qifei: QF0519-19','','',1,'hotel,apartment','assets/uploads/YSC2508.png',78,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2508-150200','beds','','Кровать YSC2508 (150×200)','YSC2508-150×200','Мягкая кровать YSC2508. Спальное место: 150×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','232*184*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2508.png',79,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('bed-ysc2508-180200','beds','','Кровать YSC2508 (180×200)','YSC2508-180×200','Мягкая кровать YSC2508. Спальное место: 180×200 см.','Качественная ткань + поролон высокой плотности + металлический каркас кровати','232*214*100 см','','','',1,'hotel,apartment','assets/uploads/YSC2508.png',80,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-21pb49','mattresses','','Матрас 21PB-49','21PB-49','Комфорт, упругость и поддержка для полноценного отдыха.','Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань','','','','',1,'hotel,apartment','assets/uploads/21PB-49.jpeg',81,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-21pb50','mattresses','','Матрас 21PB-50','21PB-50','Комфорт, поддержка и упругость для полноценного отдыха.','Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань','','','','',1,'hotel,apartment','assets/uploads/21PB-50.jpeg',82,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-32pb31','mattresses','','Матрас 32PB-31','32PB-31','Комфорт, поддержка и защита для спокойного сна.','Ткань Allergen Tech — снижает воздействие бытовых аллергенов, более гигиеничная поверхность сна','','','','',1,'hotel,apartment','assets/uploads/32PB-31.jpeg',83,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-32pb34','mattresses','','Матрас 32PB-34','32PB-34','Комфорт, поддержка и спокойный сон каждый день.','Пена высокой плотности — распределяет давление и комфортно поддерживает','','','','',1,'hotel,apartment','assets/uploads/32PB-34.jpeg',84,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-33pa27','mattresses','','Матрас 33PA-27','33PA-27','Комфорт, терморегуляция и мягкая поддержка для спокойного сна.','Комфортное соевое волокно — пышный, дышащий, натуральный материал без запаха','','','','',1,'hotel,apartment','assets/uploads/33PA-27.jpeg',85,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-34pb67','mattresses','','Матрас 34PB-67','34PB-67','Комфорт, поддержка и упругость для полноценного отдыха.','Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань','','','','',1,'hotel,apartment','assets/uploads/34PB-67.jpeg',86,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-34pb68','mattresses','','Матрас 34PB-68','34PB-68','Современный комфорт и продуманная поддержка для качественного сна.','Независимый пружинный блок — точечная поддержка тела и снижение передачи движений','','','','',1,'hotel,apartment','assets/uploads/34PB-68.jpeg',87,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-47aa23','mattresses','','Матрас 47AA-23','47AA-23','Максимальный комфорт и здоровый сон каждую ночь.','Премиальная ткань Luxury Knitted — мягкая, дышащая, приятная коже','','','','',1,'hotel,apartment','assets/uploads/47AA-23.jpeg',88,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-47aa30','mattresses','','Матрас 47AA-30','47AA-30','Комфорт, прохлада и точечная поддержка каждую ночь.','Гелевая пена с эффектом памяти — рассеивает тепло, поддерживает комфортную температуру','','','','',1,'hotel,apartment','assets/uploads/47AA-30.jpeg',89,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-47pd02','mattresses','','Матрас 47PD-02','47PD-02','Роскошный комфорт и надёжная поддержка для спокойного сна каждую ночь.','Антибактериальное волокно Surepelle — гигиеничность, защита от пылевых клещей','','','','',1,'hotel,apartment','assets/uploads/47PD-02.jpeg',90,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-lavender','mattresses','','Матрас LAVENDER','LAVENDER','Здоровый сон. Естественный комфорт.','Водная пена — мягкая, эластичная, безопасная и гипоаллергенная','','','','',1,'hotel,apartment','assets/uploads/LAVENDER.jpeg',91,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-cx03','mattresses','','Матрас CX03','CX03','Индивидуальный комфорт для каждого. Две жёсткости — две стороны — один идеальный сон.','Водная пена — экологичная, мягкая и поддерживающая','','','','',1,'hotel,apartment','assets/uploads/CX03.jpeg',92,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-osmanthus','mattresses','','Матрас OSMANTHUS','OSMANTHUS','Природный аромат, здоровый сон.','100% водная пена — безопасная, здоровая и гипоаллергенная','','','','',1,'hotel,apartment','assets/uploads/OSMANTHUS.jpeg',93,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-premiumcool','mattresses','','Матрас PREMIUM COOL','PREMIUM COOL','Индивидуальный комфорт для каждого. Один матрас — два уровня жёсткости.','Холодный шёлк — ткань с эффектом прохлады отводит тепло','','','','',1,'hotel,apartment','assets/uploads/PREMIUM_COOL.jpeg',94,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-st01familyprotect','mattresses','','Матрас FAMILY PROTECT, модель ST01','ST01 FAMILY PROTECT','Идеальный комфорт для всей семьи. Один матрас — два уровня жёсткости.','Водонепроницаемая ткань — защита от пятен и загрязнений','','','','',1,'hotel,apartment','assets/uploads/ST01_FAMILY_PROTECT.jpeg',95,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-st10','mattresses','','Матрас ST10','ST10','Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.','Водонепроницаемая ткань — защита от влаги','','','','',1,'hotel,apartment','assets/uploads/ST10.jpeg',96,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-st11','mattresses','','Матрас ST11','ST11','Индивидуальный комфорт для всей семьи. Прохлада и свежесть.','100% водная пена — мягкая, эластичная, без запаха и вредных веществ','','','','',1,'hotel,apartment','assets/uploads/ST11.jpeg',97,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-st15sanci','mattresses','','Умный матрас SANCI с регулируемым изголовьем, модель ST15','ST15 (SANCI)','Две зоны комфорта — ваш комфорт, ваш выбор. Регулируемое изголовье (с одной стороны) для чтения, просмотра ТВ и отдыха. Удобно для пожилых людей и в медицинских целях. Управление с пульта, одним нажатием.','Внутреннее наполнение: тихие пружины с плотным пенным коробом, пена с эффектом памяти, водная пена высокой плотности, экологичная ткань, основа с меха','','','','',1,'hotel,apartment','assets/uploads/ST15_SANCI.jpeg',98,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-cx01','mattresses','','Матрас CX01','CX01','Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.','100% водная пена — экологичная, безопасная и гипоаллергенная','','','','',1,'hotel,apartment','assets/uploads/CX01.jpeg',99,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('mattresses-cx02','mattresses','','Матрас CX02','CX02','Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.','100% водная пена — экологичная, безопасная и гипоаллергенная','','','','',1,'hotel,apartment','assets/uploads/CX02.jpeg',100,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-cerc3005','beds','','Кровать CE-RC3005 «Стиль и комфорт»','CE-RC3005','Идеальное сочетание современного дизайна, премиальных материалов и максимального комфорта.','Спинка — экокожа: мягкая, приятная на ощупь, износостойкая, легко чистится','','','','',1,'hotel,apartment','assets/uploads/CE-RC3005.jpeg',101,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-sz6302','beds','','Кровать SZ-6302','SZ-6302','Современный дизайн и премиальные материалы.','Обивка из натуральной кожи — мягкая, износостойкая, приятная на ощупь','','','','',1,'hotel,apartment','assets/uploads/SZ-6302.jpeg',102,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-ce2106','beds','','Кровать CE-2106 «ЛАФФИ»','CE-2106 ЛАФФИ','Стиль, комфорт и надёжность в каждой детали.','Обивка из натуральной кожи — мягкая, износостойкая, проста в уходе','','','','',1,'hotel,apartment','assets/uploads/CE-2106_ЛАФФИ.jpeg',103,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-cerc3013','beds','','Кровать CE-RC3013 «ПАФФИ»','CE-RC3013 ПАФФИ','Стиль, комфорт и гармония в каждой детали.','Качественная ткань — приятная на ощупь, устойчива к износу и выцветанию','','','','',1,'hotel,apartment','assets/uploads/CE-RC3013_ПАФФИ.jpeg',104,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-sz6506','beds','','Кровать SZ-6506','SZ-6506','Современный дизайн и максимальный комфорт.','Обивка из натуральной кожи — мягкая, прочная и приятная на ощупь','','','','',1,'hotel,apartment','assets/uploads/SZ-6506.jpeg',105,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-cerc3003','beds','','Кровать CE-RC3003','CE-RC3003','Современный минимализм и уют в каждой детали.','Обивка из качественной ткани — мягкая, приятная на ощупь, износостойкая','','','','',1,'hotel,apartment','assets/uploads/CE-RC3003.jpeg',106,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-cerc3015','beds','','Кровать CE-RC3015','CE-RC3015','Современный стиль и безупречный комфорт.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/CE-RC3015.jpeg',107,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-n107','beds','','Кровать из кожи','N107','Элегантность. Комфорт. Качество.','Кровать из высококачественной кожи сочетает современный дизайн, премиальные материалы и максимальный комфорт для здорового сна.','','','','',1,'hotel,apartment','assets/uploads/Кровать_из_кожи.jpeg',108,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-tg8116','beds','','Мягкая кровать TG-8116','TG-8116','Комфорт в каждой детали. Элегантный дизайн с глубокой стёжкой создаёт атмосферу роскоши и уюта; мягкое изголовье обеспечивает комфортную поддержку во время отдыха и чтения. Цвет: C105 серо-зелёный.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/TG-8116.jpeg',109,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-cerc3018','beds','','Кровать CE-RC3018','CE-RC3018','Ультрамягкий комфорт для вашего отдыха. Мягкая обивка и обволакивающий дизайн создают атмосферу уюта и безопасного расслабления.','Мягкая и приятная ткань букле','','','','',1,'hotel,apartment','assets/uploads/CE-RC3018.jpeg',110,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb3636zt','beds','','Кровать MB3636ZT','MB3636ZT','Роскошная мягкая обивка и лаконичное изголовье создают уютный современный образ для разных стилей спальни.','Ручная работа: прочный деревянный каркас, плотный наполнитель, износостойкая льняная ткань','','','','',1,'hotel,apartment','assets/uploads/MB3636ZT.jpeg',111,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb3681zt','beds','','Кровать MB3681ZT','MB3681ZT','Современная мягкая кровать с объёмным изголовьем и лаконичными линиями; нейтральные оттенки для любой спальни.','Детали: изголовье, царга с мягкой отделкой, деревянные ламели.','','','','',1,'hotel,apartment','assets/uploads/MB3681ZT.jpeg',112,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb3698zt','beds','','Кровать MB3698ZT','MB3698ZT','Современный минимализм и уют в каждой детали.','Обивка из качественной ткани — мягкая, приятная на ощупь, практичная','','','','',1,'hotel,apartment','assets/uploads/MB3698ZT.jpeg',113,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb3701zt','beds','','Кровать MB3701ZT','MB3701ZT','Современный минимализм и комфорт в каждой детали.','Обивка из качественной ткани — мягкая и практичная','','','','',1,'hotel,apartment','assets/uploads/MB3701ZT.jpeg',114,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb3728zt','beds','','Кровать MB3728ZT','MB3728ZT','Элегантная мягкая обивка и классическое стёганое изголовье — уютный и изысканный характер.','Детали: мягкое изголовье, прочная царга, деревянные ламели.','','','','',1,'hotel,apartment','assets/uploads/MB3728ZT.jpeg',115,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mp5218zt','beds','','Кровать MP5218ZT','MP5218ZT','Современный минимализм и комфорт в каждой детали.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/MP5218ZT.jpeg',116,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb9901zt','beds','','Кровать MB9901ZT','MB9901ZT','Роскошная мягкая обивка и выразительное геометричное изголовье для разных стилей спальни.','Практичная ткань — прочная, износостойкая, гипоаллергенная, антистатичная','','','','',1,'hotel,apartment','assets/uploads/MB9901ZT.jpeg',117,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb9907zt','beds','','Кровать MB9907ZT','MB9907ZT','Сочетание изысканного дизайна, качественных материалов и продуманной функциональности.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/MB9907ZT.jpeg',118,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mp3619zt','beds','','Кровать MP3619ZT','MP3619ZT','Роскошная мягкая обивка и эффектное стёганое изголовье для разных стилей спальни.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/MP3619ZT.jpeg',119,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mp3632zt','beds','','Кровать MP3632ZT','MP3632ZT','Идеальное сочетание изысканного дизайна, качественных материалов и продуманной функциональности.','Качественная обивка из премиальной кожи — мягкая, дышащая, износостойкая','','','','',1,'hotel,apartment','assets/uploads/MP3632ZT.jpeg',120,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('beds-mb5192zt','beds','','Кровать MB5192ZT','MB5192ZT','Современный минимализм и продуманная функциональность.','Обивка из качественной ткани — мягкая и практичная','','','','',1,'hotel,apartment','assets/uploads/MB5192ZT.jpeg',121,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-wmsf650','sofas','','Диван WMSF650','WMSF650','Современный комфорт и элегантный дизайн.','Высококачественная ткань, мягкие и упругие подушки','','','','',1,'hotel,apartment','assets/uploads/WMSF650.jpeg',122,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-ysf7239','sofas','','Модульный диван YSF-7239 «Паофу»','YSF-7239 «Паофу»','Стиль, комфорт и свобода в каждом модуле.','Высококачественные материалы: качественная ткань букле + износостойкая экокожа','','','','',1,'hotel,apartment','assets/uploads/YSF-7239_Паофу.jpeg',123,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7029','sofas','','Модульный диван CE-SF7029 «Пияфу»','CE-SF7029 «Пияфу»','Изысканный дизайн и непревзойдённый комфорт.','Качественная ткань букле; обтекаемая изогнутая форма','','','','',1,'hotel,apartment','assets/uploads/CE-SF7029_Пияфу.jpeg',124,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7013','sofas','','Модульный диван CE-SF7013 «Имосен»','CE-SF7013 «Имосен»','Комфорт, стиль и функциональность в каждой детали.','Качественная и приятная на ощупь ткань','','','','',1,'hotel,apartment','assets/uploads/CE-SF7013_Имосен.jpeg',125,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7021','sofas','','Современный диван CE-SF7021 «МЕАНИ»','CE-SF7021 «МЕАНИ»','Современный диван для комфортной жизни. Элегантные плавные линии и мягкие формы создают уютную атмосферу в вашем доме. Цвет: C195 коричневый.','Качественные материалы: букле высокого качества, износостойкая ткань','','','','',1,'hotel,apartment','assets/uploads/CE-SF7021_МЕАНИ.jpeg',126,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7030','sofas','','Модульный диван CE-SF7030 «Макиато»','CE-SF7030 «Макиато»','Уют, стиль и максимальный комфорт в каждой детали.','Качественная приятная на ощупь ткань','','','','',1,'hotel,apartment','assets/uploads/CE-SF7030_Макиато.jpeg',127,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-ysf7241','sofas','','Модульный диван YSF-7241 «Линшан»','YSF-7241 «Линшан»','Современный дизайн и максимальный комфорт.','Качественная ткань, приятная на ощупь','','','','',1,'hotel,apartment','assets/uploads/YSF-7241_Линшан.jpeg',128,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7012','sofas','','Модульный диван CE-SF7012 «ДИЛАН»','CE-SF7012 «ДИЛАН»','Современный стиль и комфорт в каждой детали.','Качественная ткань, приятная на ощупь','','','','',1,'hotel,apartment','assets/uploads/CE-SF7012_ДИЛАН.jpeg',129,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('sofas-cesf7006','sofas','','Модульный диван CE-SF7006 «БРЕЙЗЕР»','CE-SF7006 «БРЕЙЗЕР»','Стиль, комфорт и функциональность в каждой детали.','Качественная ткань букле, приятная на ощупь','','','','',1,'hotel,apartment','assets/uploads/CE-SF7006_БРЕЙЗЕР.jpeg',130,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('chairs-n130','chairs','','Массажное кресло','N130','Ваш личный центр расслабления и здоровья.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',131,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('chairs-n131','chairs','','Массажное кресло','N131','Расслабление и комфорт в каждом движении.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',132,1);
INSERT INTO products (slug,category,subcategory,name,art,descr,material,sizes,color,destination,packing,custom,objects,image,sort_order,is_published) VALUES ('chairs-n132','chairs','','Массажное кресло-реклайнер','N132','Максимальное расслабление и забота о вашем теле.','Премиальные материалы','','','','',1,'hotel,apartment','assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',133,1);
