<?php
/** Товары с фотографиями (133 позиции). */
return [
  [
    'slug' => 'sofa-ysf25056',
    'category' => 'sofas',
    'name' => 'Диван YSF25056 (Модульный диван (левая 2-местная с подло)',
    'art' => 'YSF25056',
    'descr' => 'Модульный диван (левая 2-местная с подлокотником + правая 2-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H946.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '252*103*64 см',
    'color' => 'H946',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25056.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25056-sec1',
    'category' => 'sofas',
    'name' => 'Левая 2-местная секция с подлокотником (к дивану YSF25056)',
    'art' => 'YSF25056-SEC',
    'descr' => 'Левая 2-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '126*103*64 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25056.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25056-sec2',
    'category' => 'sofas',
    'name' => 'Правая 2-местная секция с подлокотником (к дивану YSF25056)',
    'art' => 'YSF25056-SEC',
    'descr' => 'Правая 2-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '126*103*64 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25056.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25113',
    'category' => 'sofas',
    'name' => 'Диван YSF25113 (Компрессионный диван)',
    'art' => 'YSF25113',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '312*105*80 см',
    'color' => '',
    'packing' => '(1270*37*37)*2/1220*310*310',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25113.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25118',
    'category' => 'sofas',
    'name' => 'Диван YSF25118 (Компрессионный диван)',
    'art' => 'YSF25118',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '196*100*58 см',
    'color' => '',
    'packing' => '116*38*38',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25118.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25003k83-sec0',
    'category' => 'sofas',
    'name' => 'Модульный диван (левая 3-местная секция + правый шезлонг) (к дивану YSF25003（K83）)',
    'art' => 'YSF25003（K83）-SEC',
    'descr' => 'Модульный диван (левая 3-местная секция + правый шезлонг). Стандартная комплектация. Ткань/обивка: LVZ52-03.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '2760*1730*580 см',
    'color' => 'LVZ52-03',
    'packing' => '40*43*110/37*38*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25003_K83.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25003k83-sec1',
    'category' => 'sofas',
    'name' => 'Левая 3-местная секция (к дивану YSF25003（K83）)',
    'art' => 'YSF25003（K83）-SEC',
    'descr' => 'Левая 3-местная секция. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '1730*1060*580 см',
    'color' => '',
    'packing' => '40*43*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25003_K83.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25003k83-sec2',
    'category' => 'sofas',
    'name' => 'Правый шезлонг (рекамье) (к дивану YSF25003（K83）)',
    'art' => 'YSF25003（K83）-SEC',
    'descr' => 'Правый шезлонг (рекамье). ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '1730*1030*580 см',
    'color' => '',
    'packing' => '37*38*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25003_K83.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'accessory-pillow-8',
    'category' => 'sofas',
    'name' => 'Декоративная подушка',
    'art' => 'YSF25003（K83）-P',
    'descr' => 'Декоративная подушка. Декоративная подушка в комплекте к дивану YSF25003（K83）.',
    'material' => 'LVZ52-03',
    'sizes' => '',
    'color' => 'LVZ52-03',
    'packing' => '',
    'custom' => false,
    'objects' => [],
    'image' => 'assets/uploads/YSF25003_K83.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'accessory-pillow-9',
    'category' => 'sofas',
    'name' => 'Поясничная подушка',
    'art' => 'YSF25003（K83）-P',
    'descr' => 'Поясничная подушка. Декоративная подушка в комплекте к дивану YSF25003（K83）.',
    'material' => 'LVZ52-03',
    'sizes' => '',
    'color' => 'LVZ52-03',
    'packing' => '',
    'custom' => false,
    'objects' => [],
    'image' => 'assets/uploads/YSF25003_K83.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25004k85',
    'category' => 'sofas',
    'name' => 'Диван YSF25004（K85） (Четырёхместный диван)',
    'art' => 'YSF25004（K85）',
    'descr' => 'Четырёхместный диван. Стандартная комплектация. Ткань/обивка: Вельвет.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя
+ вельветовая ткань',
    'sizes' => '3070*1040*730 см',
    'color' => 'Вельвет',
    'packing' => '(35*35*108）*2+（30*30*88）',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25004_K85.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25006',
    'category' => 'sofas',
    'name' => 'Диван YSF25006',
    'art' => 'YSF25006',
    'descr' => 'Модель YSF25006. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25006.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25007',
    'category' => 'sofas',
    'name' => 'Диван YSF25007',
    'art' => 'YSF25007',
    'descr' => 'Модель YSF25007. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25007.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25008k91',
    'category' => 'sofas',
    'name' => 'Диван YSF25008（K91） (Двухместный компрессионный диван)',
    'art' => 'YSF25008（K91）',
    'descr' => 'Двухместный компрессионный диван. Стандартная комплектация. Ткань/обивка: «Гэдяо-8».',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя
+ вельветовая ткань',
    'sizes' => '2060*1040*700 см',
    'color' => '«Гэдяо-8»',
    'packing' => '110*75*39',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25008_K91.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25025k118',
    'category' => 'sofas',
    'name' => 'Диван YSF25025（K118） (Компрессионный модульный диван (левая 1-)',
    'art' => 'YSF25025（K118）',
    'descr' => 'Компрессионный модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: S639-34.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '304*102*73 см',
    'color' => 'S639-34',
    'packing' => '(33*33*117）*2+（31*31*87）',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25025_K118.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25025k118-sec1',
    'category' => 'sofas',
    'name' => 'Левая 1-местная секция с подлокотником (к дивану YSF25025（K118）)',
    'art' => 'YSF25025（K118）-SEC',
    'descr' => 'Левая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '111*102*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25025_K118.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25025k118-sec2',
    'category' => 'sofas',
    'name' => '1-местная секция без подлокотников (к дивану YSF25025（K118）)',
    'art' => 'YSF25025（K118）-SEC',
    'descr' => '1-местная секция без подлокотников. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '82*102*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25025_K118.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25025k118-sec3',
    'category' => 'sofas',
    'name' => 'Правая 1-местная секция с подлокотником (к дивану YSF25025（K118）)',
    'art' => 'YSF25025（K118）-SEC',
    'descr' => 'Правая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '111*102*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25025_K118.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25042',
    'category' => 'sofas',
    'name' => 'Диван YSF25042 (Модульный диван (левая 1-местная с подло)',
    'art' => 'YSF25042',
    'descr' => 'Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: CKS063-12.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань премиум-класса',
    'sizes' => '276*112*71 см',
    'color' => 'CKS063-12',
    'packing' => '28*28*110/3',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25042.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25042-sec1',
    'category' => 'sofas',
    'name' => 'Левая 1-местная секция с подлокотником (к дивану YSF25042)',
    'art' => 'YSF25042-SEC',
    'descr' => 'Левая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92*112*71 см',
    'color' => '',
    'packing' => '28*28*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25042.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25042-sec2',
    'category' => 'sofas',
    'name' => '1-местная секция без подлокотников (к дивану YSF25042)',
    'art' => 'YSF25042-SEC',
    'descr' => '1-местная секция без подлокотников. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92*112*71 см',
    'color' => '',
    'packing' => '28*28*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25042.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25042-sec3',
    'category' => 'sofas',
    'name' => 'Правая 1-местная секция с подлокотником (к дивану YSF25042)',
    'art' => 'YSF25042-SEC',
    'descr' => 'Правая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92*112*71 см',
    'color' => '',
    'packing' => '28*28*110',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25042.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25050',
    'category' => 'sofas',
    'name' => 'Диван YSF25050 (Модульный диван (левая 1-местная с подло)',
    'art' => 'YSF25050',
    'descr' => 'Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H939+H940+H941.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '281*94*64 см',
    'color' => 'H939+H940+H941',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25050.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25050-sec1',
    'category' => 'sofas',
    'name' => 'Левая 1-местная секция с подлокотником (к дивану YSF25050)',
    'art' => 'YSF25050-SEC',
    'descr' => 'Левая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '95*94*64 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25050.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25050-sec2',
    'category' => 'sofas',
    'name' => '1-местная секция без подлокотников (к дивану YSF25050)',
    'art' => 'YSF25050-SEC',
    'descr' => '1-местная секция без подлокотников. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '91*94*64 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25050.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25050-sec3',
    'category' => 'sofas',
    'name' => 'Правая 1-местная секция с подлокотником (к дивану YSF25050)',
    'art' => 'YSF25050-SEC',
    'descr' => 'Правая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '95*94*64 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25050.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25052',
    'category' => 'sofas',
    'name' => 'Диван YSF25052 (Модульный диван (левая 1-местная с подло)',
    'art' => 'YSF25052',
    'descr' => 'Модульный диван (левая 1-местная с подлокотником + 1-местная без подлокотников + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H935+H936.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '273*91*65 см',
    'color' => 'H935+H936',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25052-sec1',
    'category' => 'sofas',
    'name' => 'Левая 1-местная секция с подлокотником (к дивану YSF25052)',
    'art' => 'YSF25052-SEC',
    'descr' => 'Левая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '91*91*65 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25052-sec2',
    'category' => 'sofas',
    'name' => '1-местная секция без подлокотников (к дивану YSF25052)',
    'art' => 'YSF25052-SEC',
    'descr' => '1-местная секция без подлокотников. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '91*91*65 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25052-sec3',
    'category' => 'sofas',
    'name' => 'Правая 1-местная секция с подлокотником (к дивану YSF25052)',
    'art' => 'YSF25052-SEC',
    'descr' => 'Правая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '91*91*65 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'accessory-pillow-30',
    'category' => 'sofas',
    'name' => 'Декоративная подушка 1',
    'art' => 'YSF25052-P',
    'descr' => 'Декоративная подушка 1. Декоративная подушка в комплекте к дивану YSF25052.',
    'material' => 'H935',
    'sizes' => '',
    'color' => 'H935',
    'packing' => '',
    'custom' => false,
    'objects' => [],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'accessory-pillow-31',
    'category' => 'sofas',
    'name' => 'Декоративная подушка 2',
    'art' => 'YSF25052-P',
    'descr' => 'Декоративная подушка 2. Декоративная подушка в комплекте к дивану YSF25052.',
    'material' => 'H936',
    'sizes' => '',
    'color' => 'H936',
    'packing' => '',
    'custom' => false,
    'objects' => [],
    'image' => 'assets/uploads/YSF25052_Левая_1-местная_секция_с_.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25053-sec0',
    'category' => 'sofas',
    'name' => 'Модульный диван (левая 1-местная с подлокотником + пуф/подст (к дивану YSF25053)',
    'art' => 'YSF25053-SEC',
    'descr' => 'Модульный диван (левая 1-местная с подлокотником + пуф/подставка для ног + правая 1-местная с подлокотником). Стандартная комплектация. Ткань/обивка: H937+H938.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '276*92*73 см',
    'color' => 'H937+H938',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25053.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25053-sec1',
    'category' => 'sofas',
    'name' => 'Левая 1-местная секция с подлокотником (к дивану YSF25053)',
    'art' => 'YSF25053-SEC',
    'descr' => 'Левая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92*92*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25053.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25053-sec2',
    'category' => 'sofas',
    'name' => 'Пуф / подставка для ног (к дивану YSF25053)',
    'art' => 'YSF25053-SEC',
    'descr' => 'Пуф / подставка для ног. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92**92*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25053.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25053-sec3',
    'category' => 'sofas',
    'name' => 'Правая 1-местная секция с подлокотником (к дивану YSF25053)',
    'art' => 'YSF25053-SEC',
    'descr' => 'Правая 1-местная секция с подлокотником. ',
    'material' => 'Высокоэластичный поролон, качественная обивка',
    'sizes' => '92*92*73 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25053.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'accessory-pillow-36',
    'category' => 'sofas',
    'name' => 'Декоративная подушка',
    'art' => 'YSF25053-P',
    'descr' => 'Декоративная подушка. Декоративная подушка в комплекте к дивану YSF25053.',
    'material' => 'H938',
    'sizes' => '',
    'color' => 'H938',
    'packing' => '',
    'custom' => false,
    'objects' => [],
    'image' => 'assets/uploads/YSF25053.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25011',
    'category' => 'sofas',
    'name' => 'Диван YSF25011',
    'art' => 'YSF25011',
    'descr' => 'Модель YSF25011. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25011.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25016k106',
    'category' => 'sofas',
    'name' => 'Диван YSF25016（K106） (Компрессионный диван)',
    'art' => 'YSF25016（K106）',
    'descr' => 'Компрессионный диван. Стандартная комплектация. Ткань/обивка: MA-05.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '102*80*62 см',
    'color' => 'MA-05',
    'packing' => '90*28*28',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25016_K106.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25021k113',
    'category' => 'sofas',
    'name' => 'Диван YSF25021（K113） (Компрессионный диван)',
    'art' => 'YSF25021（K113）',
    'descr' => 'Компрессионный диван. Стандартная комплектация. Ткань/обивка: 639-12 (оранжевый) / 639-23 (синий).',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ шенилловая ткань',
    'sizes' => '100*83*77 см',
    'color' => '639-12 (оранжевый) / 639-23 (синий)',
    'packing' => '28*28*88',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25021_K113.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25033',
    'category' => 'sofas',
    'name' => 'Диван YSF25033 (Компрессионный диван)',
    'art' => 'YSF25033',
    'descr' => 'Компрессионный диван. Стандартная комплектация. Ткань/обивка: H932.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '84*104*84 см',
    'color' => 'H932',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25033.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25048',
    'category' => 'sofas',
    'name' => 'Диван YSF25048 (Компрессионный диван)',
    'art' => 'YSF25048',
    'descr' => 'Компрессионный диван. Стандартная комплектация. Ткань/обивка: H933.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '95*108*68 см',
    'color' => 'H933',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25048.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25057',
    'category' => 'sofas',
    'name' => 'Диван YSF25057 (Одноместный компрессионный диван)',
    'art' => 'YSF25057',
    'descr' => 'Одноместный компрессионный диван. Стандартная комплектация. Ткань/обивка: H942.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '101*101*82 см',
    'color' => 'H942',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25057.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25060',
    'category' => 'sofas',
    'name' => 'Диван YSF25060 (Компрессионный диван, 1-местный)',
    'art' => 'YSF25060',
    'descr' => 'Компрессионный диван, 1-местный. Стандартная комплектация. Ткань/обивка: 651-7.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '110*106*66 см',
    'color' => '651-7',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25060.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25061',
    'category' => 'sofas',
    'name' => 'Диван YSF25061 (Компрессионный диван)',
    'art' => 'YSF25061',
    'descr' => 'Компрессионный диван. Стандартная комплектация. Ткань/обивка: Синий.',
    'material' => 'Качественная ткань + высокоэластичный поролон + девятиканальное волокно',
    'sizes' => '98*90*75 см',
    'color' => 'Синий',
    'packing' => '96*35*35',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => '',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25101',
    'category' => 'sofas',
    'name' => 'Диван YSF25101',
    'art' => 'YSF25101',
    'descr' => 'Модель YSF25101. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25101.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25106',
    'category' => 'sofas',
    'name' => 'Диван YSF25106',
    'art' => 'YSF25106',
    'descr' => 'Модель YSF25106. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25106.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25107',
    'category' => 'sofas',
    'name' => 'Диван YSF25107 (Компрессионный диван)',
    'art' => 'YSF25107',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань',
    'sizes' => '100*83*75 см',
    'color' => '',
    'packing' => '32*32*92',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25107.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25119',
    'category' => 'sofas',
    'name' => 'Диван YSF25119 (Компрессионный диван)',
    'art' => 'YSF25119',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «тедди»',
    'sizes' => '166*97*76 см',
    'color' => '',
    'packing' => '120*39*39',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25119.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25120',
    'category' => 'sofas',
    'name' => 'Диван YSF25120 (Компрессионный диван)',
    'art' => 'YSF25120',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + эластичная ткань',
    'sizes' => '90*85*67 см',
    'color' => '',
    'packing' => '93*29*29',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25120.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25121',
    'category' => 'sofas',
    'name' => 'Диван YSF25121 (Компрессионный диван)',
    'art' => 'YSF25121',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + эластичная ткань',
    'sizes' => '85*73*71 см',
    'color' => '',
    'packing' => '81*27*27',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25121.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25123',
    'category' => 'sofas',
    'name' => 'Диван YSF25123 (Компрессионный диван)',
    'art' => 'YSF25123',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань',
    'sizes' => '100*100*77 см',
    'color' => '',
    'packing' => '81*27*27',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25123.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25124',
    'category' => 'sofas',
    'name' => 'Диван YSF25124',
    'art' => 'YSF25124',
    'descr' => 'Модель YSF25124. Подробные характеристики по запросу.',
    'material' => 'Высокоэластичный поролон, качественная обивочная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25124.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25005k88',
    'category' => 'sofas',
    'name' => 'Диван YSF25005（K88） (Компрессионный диван)',
    'art' => 'YSF25005（K88）',
    'descr' => 'Компрессионный диван. Стандартная комплектация. ',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань',
    'sizes' => '80*80*70 см',
    'color' => '',
    'packing' => '87*27*27',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25005_K88.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25009k92',
    'category' => 'sofas',
    'name' => 'Диван YSF25009（K92） (Одноместный диван)',
    'art' => 'YSF25009（K92）',
    'descr' => 'Одноместный диван. Стандартная комплектация. Ткань/обивка: Вельвет.',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + вельветовая ткань',
    'sizes' => '900*900*730 см',
    'color' => 'Вельвет',
    'packing' => '109*32*32',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25009_K92.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofa-ysf25010k93',
    'category' => 'sofas',
    'name' => 'Диван YSF25010（K93） (Одноместный диван)',
    'art' => 'YSF25010（K93）',
    'descr' => 'Одноместный диван. Стандартная комплектация. Ткань/обивка: Ткань «тедди».',
    'material' => 'Специальный высокоэластичный компрессионный поролон
+ обивка из шёлкового наполнителя + ткань «овчина»',
    'sizes' => '750*930*770 см',
    'color' => 'Ткань «тедди»',
    'packing' => '82*31*31',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF25010_K93.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2509-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2509 (120×200)',
    'art' => 'YSC2509-120×200',
    'descr' => 'Мягкая кровать YSC2509. Спальное место: 120×200 см. Обивка: Jie\'en: SWR569C-1.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '233*165*101 см',
    'color' => 'Jie\'en: SWR569C-1',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2509.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2509-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2509 (150×200)',
    'art' => 'YSC2509-150×200',
    'descr' => 'Мягкая кровать YSC2509. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '233*195*101 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2509.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2509-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2509 (180×200)',
    'art' => 'YSC2509-180×200',
    'descr' => 'Мягкая кровать YSC2509. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '233*225*101 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2509.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2501-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2501 (120×200)',
    'art' => 'YSC2501-120×200',
    'descr' => 'Мягкая кровать YSC2501. Спальное место: 120×200 см. Обивка: Qifei: QF0519-7.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*154*100 см',
    'color' => 'Qifei: QF0519-7',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2501.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2501-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2501 (150×200)',
    'art' => 'YSC2501-150×200',
    'descr' => 'Мягкая кровать YSC2501. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*184*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2501.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2501-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2501 (180×200)',
    'art' => 'YSC2501-180×200',
    'descr' => 'Мягкая кровать YSC2501. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*214*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2501.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2502-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2502 (120×200)',
    'art' => 'YSC2502-120×200',
    'descr' => 'Мягкая кровать YSC2502. Спальное место: 120×200 см. Обивка: Qifei: QF0519-13 + Luoweizan LVZ2005-02.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*154*100 см',
    'color' => 'Qifei: QF0519-13 + Luoweizan LVZ2005-02',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2502.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2502-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2502 (150×200)',
    'art' => 'YSC2502-150×200',
    'descr' => 'Мягкая кровать YSC2502. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*184*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2502.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2502-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2502 (180×200)',
    'art' => 'YSC2502-180×200',
    'descr' => 'Мягкая кровать YSC2502. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '237*214*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2502.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2503-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2503 (120×200)',
    'art' => 'YSC2503-120×200',
    'descr' => 'Мягкая кровать YSC2503. Спальное место: 120×200 см. Обивка: Qifei: QF0519-9.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '241*155*100 см',
    'color' => 'Qifei: QF0519-9',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2503.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2503-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2503 (150×200)',
    'art' => 'YSC2503-150×200',
    'descr' => 'Мягкая кровать YSC2503. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '241*185*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2503.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2503-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2503 (180×200)',
    'art' => 'YSC2503-180×200',
    'descr' => 'Мягкая кровать YSC2503. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '241*215*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2503.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2505-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2505 (120×200)',
    'art' => 'YSC2505-120×200',
    'descr' => 'Мягкая кровать YSC2505. Спальное место: 120×200 см. Обивка: Qifei: QF0519-3.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '242*155*107 см',
    'color' => 'Qifei: QF0519-3',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2505.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2505-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2505 (150×200)',
    'art' => 'YSC2505-150×200',
    'descr' => 'Мягкая кровать YSC2505. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '242*185*107 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2505.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2505-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2505 (180×200)',
    'art' => 'YSC2505-180×200',
    'descr' => 'Мягкая кровать YSC2505. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '242*215*107 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2505.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2506-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2506 (120×200)',
    'art' => 'YSC2506-120×200',
    'descr' => 'Мягкая кровать YSC2506. Спальное место: 120×200 см. Обивка: Qifei: QF0519-17.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '235*154*97 см',
    'color' => 'Qifei: QF0519-17',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2506.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2506-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2506 (150×200)',
    'art' => 'YSC2506-150×200',
    'descr' => 'Мягкая кровать YSC2506. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '235*184*97 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2506.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2506-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2506 (180×200)',
    'art' => 'YSC2506-180×200',
    'descr' => 'Мягкая кровать YSC2506. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '235*214*97 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2506.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2507-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2507 (120×200)',
    'art' => 'YSC2507-120×200',
    'descr' => 'Мягкая кровать YSC2507. Спальное место: 120×200 см. Обивка: Qifei: QF0519-16.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '240*154*97 см',
    'color' => 'Qifei: QF0519-16',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2507.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2507-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2507 (150×200)',
    'art' => 'YSC2507-150×200',
    'descr' => 'Мягкая кровать YSC2507. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '240*184*97 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2507.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2507-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2507 (180×200)',
    'art' => 'YSC2507-180×200',
    'descr' => 'Мягкая кровать YSC2507. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '240*214*97 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2507.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2508-120200',
    'category' => 'beds',
    'name' => 'Кровать YSC2508 (120×200)',
    'art' => 'YSC2508-120×200',
    'descr' => 'Мягкая кровать YSC2508. Спальное место: 120×200 см. Обивка: Qifei: QF0519-19.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '232*154*100 см',
    'color' => 'Qifei: QF0519-19',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2508.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2508-150200',
    'category' => 'beds',
    'name' => 'Кровать YSC2508 (150×200)',
    'art' => 'YSC2508-150×200',
    'descr' => 'Мягкая кровать YSC2508. Спальное место: 150×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '232*184*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2508.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'bed-ysc2508-180200',
    'category' => 'beds',
    'name' => 'Кровать YSC2508 (180×200)',
    'art' => 'YSC2508-180×200',
    'descr' => 'Мягкая кровать YSC2508. Спальное место: 180×200 см.',
    'material' => 'Качественная ткань + поролон высокой плотности + металлический каркас кровати',
    'sizes' => '232*214*100 см',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSC2508.png',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-21pb49',
    'category' => 'mattresses',
    'name' => 'Матрас 21PB-49',
    'art' => '21PB-49',
    'descr' => 'Комфорт, упругость и поддержка для полноценного отдыха.',
    'material' => 'Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/21PB-49.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-21pb50',
    'category' => 'mattresses',
    'name' => 'Матрас 21PB-50',
    'art' => '21PB-50',
    'descr' => 'Комфорт, поддержка и упругость для полноценного отдыха.',
    'material' => 'Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/21PB-50.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-32pb31',
    'category' => 'mattresses',
    'name' => 'Матрас 32PB-31',
    'art' => '32PB-31',
    'descr' => 'Комфорт, поддержка и защита для спокойного сна.',
    'material' => 'Ткань Allergen Tech — снижает воздействие бытовых аллергенов, более гигиеничная поверхность сна',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/32PB-31.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-32pb34',
    'category' => 'mattresses',
    'name' => 'Матрас 32PB-34',
    'art' => '32PB-34',
    'descr' => 'Комфорт, поддержка и спокойный сон каждый день.',
    'material' => 'Пена высокой плотности — распределяет давление и комфортно поддерживает',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/32PB-34.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-33pa27',
    'category' => 'mattresses',
    'name' => 'Матрас 33PA-27',
    'art' => '33PA-27',
    'descr' => 'Комфорт, терморегуляция и мягкая поддержка для спокойного сна.',
    'material' => 'Комфортное соевое волокно — пышный, дышащий, натуральный материал без запаха',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/33PA-27.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-34pb67',
    'category' => 'mattresses',
    'name' => 'Матрас 34PB-67',
    'art' => '34PB-67',
    'descr' => 'Комфорт, поддержка и упругость для полноценного отдыха.',
    'material' => 'Роскошный трикотаж — мягкая, эластичная и приятная к телу ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/34PB-67.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-34pb68',
    'category' => 'mattresses',
    'name' => 'Матрас 34PB-68',
    'art' => '34PB-68',
    'descr' => 'Современный комфорт и продуманная поддержка для качественного сна.',
    'material' => 'Независимый пружинный блок — точечная поддержка тела и снижение передачи движений',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/34PB-68.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-47aa23',
    'category' => 'mattresses',
    'name' => 'Матрас 47AA-23',
    'art' => '47AA-23',
    'descr' => 'Максимальный комфорт и здоровый сон каждую ночь.',
    'material' => 'Премиальная ткань Luxury Knitted — мягкая, дышащая, приятная коже',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/47AA-23.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-47aa30',
    'category' => 'mattresses',
    'name' => 'Матрас 47AA-30',
    'art' => '47AA-30',
    'descr' => 'Комфорт, прохлада и точечная поддержка каждую ночь.',
    'material' => 'Гелевая пена с эффектом памяти — рассеивает тепло, поддерживает комфортную температуру',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/47AA-30.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-47pd02',
    'category' => 'mattresses',
    'name' => 'Матрас 47PD-02',
    'art' => '47PD-02',
    'descr' => 'Роскошный комфорт и надёжная поддержка для спокойного сна каждую ночь.',
    'material' => 'Антибактериальное волокно Surepelle — гигиеничность, защита от пылевых клещей',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/47PD-02.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-lavender',
    'category' => 'mattresses',
    'name' => 'Матрас LAVENDER',
    'art' => 'LAVENDER',
    'descr' => 'Здоровый сон. Естественный комфорт.',
    'material' => 'Водная пена — мягкая, эластичная, безопасная и гипоаллергенная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/LAVENDER.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-cx03',
    'category' => 'mattresses',
    'name' => 'Матрас CX03',
    'art' => 'CX03',
    'descr' => 'Индивидуальный комфорт для каждого. Две жёсткости — две стороны — один идеальный сон.',
    'material' => 'Водная пена — экологичная, мягкая и поддерживающая',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CX03.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-osmanthus',
    'category' => 'mattresses',
    'name' => 'Матрас OSMANTHUS',
    'art' => 'OSMANTHUS',
    'descr' => 'Природный аромат, здоровый сон.',
    'material' => '100% водная пена — безопасная, здоровая и гипоаллергенная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/OSMANTHUS.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-premiumcool',
    'category' => 'mattresses',
    'name' => 'Матрас PREMIUM COOL',
    'art' => 'PREMIUM COOL',
    'descr' => 'Индивидуальный комфорт для каждого. Один матрас — два уровня жёсткости.',
    'material' => 'Холодный шёлк — ткань с эффектом прохлады отводит тепло',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/PREMIUM_COOL.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-st01familyprotect',
    'category' => 'mattresses',
    'name' => 'Матрас FAMILY PROTECT, модель ST01',
    'art' => 'ST01 FAMILY PROTECT',
    'descr' => 'Идеальный комфорт для всей семьи. Один матрас — два уровня жёсткости.',
    'material' => 'Водонепроницаемая ткань — защита от пятен и загрязнений',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/ST01_FAMILY_PROTECT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-st10',
    'category' => 'mattresses',
    'name' => 'Матрас ST10',
    'art' => 'ST10',
    'descr' => 'Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.',
    'material' => 'Водонепроницаемая ткань — защита от влаги',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/ST10.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-st11',
    'category' => 'mattresses',
    'name' => 'Матрас ST11',
    'art' => 'ST11',
    'descr' => 'Индивидуальный комфорт для всей семьи. Прохлада и свежесть.',
    'material' => '100% водная пена — мягкая, эластичная, без запаха и вредных веществ',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/ST11.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-st15sanci',
    'category' => 'mattresses',
    'name' => 'Умный матрас SANCI с регулируемым изголовьем, модель ST15',
    'art' => 'ST15 (SANCI)',
    'descr' => 'Две зоны комфорта — ваш комфорт, ваш выбор. Регулируемое изголовье (с одной стороны) для чтения, просмотра ТВ и отдыха. Удобно для пожилых людей и в медицинских целях. Управление с пульта, одним нажатием.',
    'material' => 'Внутреннее наполнение: тихие пружины с плотным пенным коробом, пена с эффектом памяти, водная пена высокой плотности, экологичная ткань, основа с меха',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/ST15_SANCI.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-cx01',
    'category' => 'mattresses',
    'name' => 'Матрас CX01',
    'art' => 'CX01',
    'descr' => 'Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.',
    'material' => '100% водная пена — экологичная, безопасная и гипоаллергенная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CX01.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'mattresses-cx02',
    'category' => 'mattresses',
    'name' => 'Матрас CX02',
    'art' => 'CX02',
    'descr' => 'Индивидуальный комфорт для всей семьи. Один матрас — два уровня жёсткости.',
    'material' => '100% водная пена — экологичная, безопасная и гипоаллергенная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CX02.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-cerc3005',
    'category' => 'beds',
    'name' => 'Кровать CE-RC3005 «Стиль и комфорт»',
    'art' => 'CE-RC3005',
    'descr' => 'Идеальное сочетание современного дизайна, премиальных материалов и максимального комфорта.',
    'material' => 'Спинка — экокожа: мягкая, приятная на ощупь, износостойкая, легко чистится',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-RC3005.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-sz6302',
    'category' => 'beds',
    'name' => 'Кровать SZ-6302',
    'art' => 'SZ-6302',
    'descr' => 'Современный дизайн и премиальные материалы.',
    'material' => 'Обивка из натуральной кожи — мягкая, износостойкая, приятная на ощупь',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/SZ-6302.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-ce2106',
    'category' => 'beds',
    'name' => 'Кровать CE-2106 «ЛАФФИ»',
    'art' => 'CE-2106 ЛАФФИ',
    'descr' => 'Стиль, комфорт и надёжность в каждой детали.',
    'material' => 'Обивка из натуральной кожи — мягкая, износостойкая, проста в уходе',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-2106_ЛАФФИ.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-cerc3013',
    'category' => 'beds',
    'name' => 'Кровать CE-RC3013 «ПАФФИ»',
    'art' => 'CE-RC3013 ПАФФИ',
    'descr' => 'Стиль, комфорт и гармония в каждой детали.',
    'material' => 'Качественная ткань — приятная на ощупь, устойчива к износу и выцветанию',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-RC3013_ПАФФИ.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-sz6506',
    'category' => 'beds',
    'name' => 'Кровать SZ-6506',
    'art' => 'SZ-6506',
    'descr' => 'Современный дизайн и максимальный комфорт.',
    'material' => 'Обивка из натуральной кожи — мягкая, прочная и приятная на ощупь',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/SZ-6506.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-cerc3003',
    'category' => 'beds',
    'name' => 'Кровать CE-RC3003',
    'art' => 'CE-RC3003',
    'descr' => 'Современный минимализм и уют в каждой детали.',
    'material' => 'Обивка из качественной ткани — мягкая, приятная на ощупь, износостойкая',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-RC3003.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-cerc3015',
    'category' => 'beds',
    'name' => 'Кровать CE-RC3015',
    'art' => 'CE-RC3015',
    'descr' => 'Современный стиль и безупречный комфорт.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-RC3015.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-n107',
    'category' => 'beds',
    'name' => 'Кровать из кожи',
    'art' => 'N107',
    'descr' => 'Элегантность. Комфорт. Качество.',
    'material' => 'Кровать из высококачественной кожи сочетает современный дизайн, премиальные материалы и максимальный комфорт для здорового сна.',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/Кровать_из_кожи.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-tg8116',
    'category' => 'beds',
    'name' => 'Мягкая кровать TG-8116',
    'art' => 'TG-8116',
    'descr' => 'Комфорт в каждой детали. Элегантный дизайн с глубокой стёжкой создаёт атмосферу роскоши и уюта; мягкое изголовье обеспечивает комфортную поддержку во время отдыха и чтения. Цвет: C105 серо-зелёный.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/TG-8116.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-cerc3018',
    'category' => 'beds',
    'name' => 'Кровать CE-RC3018',
    'art' => 'CE-RC3018',
    'descr' => 'Ультрамягкий комфорт для вашего отдыха. Мягкая обивка и обволакивающий дизайн создают атмосферу уюта и безопасного расслабления.',
    'material' => 'Мягкая и приятная ткань букле',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-RC3018.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb3636zt',
    'category' => 'beds',
    'name' => 'Кровать MB3636ZT',
    'art' => 'MB3636ZT',
    'descr' => 'Роскошная мягкая обивка и лаконичное изголовье создают уютный современный образ для разных стилей спальни.',
    'material' => 'Ручная работа: прочный деревянный каркас, плотный наполнитель, износостойкая льняная ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB3636ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb3681zt',
    'category' => 'beds',
    'name' => 'Кровать MB3681ZT',
    'art' => 'MB3681ZT',
    'descr' => 'Современная мягкая кровать с объёмным изголовьем и лаконичными линиями; нейтральные оттенки для любой спальни.',
    'material' => 'Детали: изголовье, царга с мягкой отделкой, деревянные ламели.',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB3681ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb3698zt',
    'category' => 'beds',
    'name' => 'Кровать MB3698ZT',
    'art' => 'MB3698ZT',
    'descr' => 'Современный минимализм и уют в каждой детали.',
    'material' => 'Обивка из качественной ткани — мягкая, приятная на ощупь, практичная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB3698ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb3701zt',
    'category' => 'beds',
    'name' => 'Кровать MB3701ZT',
    'art' => 'MB3701ZT',
    'descr' => 'Современный минимализм и комфорт в каждой детали.',
    'material' => 'Обивка из качественной ткани — мягкая и практичная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB3701ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb3728zt',
    'category' => 'beds',
    'name' => 'Кровать MB3728ZT',
    'art' => 'MB3728ZT',
    'descr' => 'Элегантная мягкая обивка и классическое стёганое изголовье — уютный и изысканный характер.',
    'material' => 'Детали: мягкое изголовье, прочная царга, деревянные ламели.',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB3728ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mp5218zt',
    'category' => 'beds',
    'name' => 'Кровать MP5218ZT',
    'art' => 'MP5218ZT',
    'descr' => 'Современный минимализм и комфорт в каждой детали.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MP5218ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb9901zt',
    'category' => 'beds',
    'name' => 'Кровать MB9901ZT',
    'art' => 'MB9901ZT',
    'descr' => 'Роскошная мягкая обивка и выразительное геометричное изголовье для разных стилей спальни.',
    'material' => 'Практичная ткань — прочная, износостойкая, гипоаллергенная, антистатичная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB9901ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb9907zt',
    'category' => 'beds',
    'name' => 'Кровать MB9907ZT',
    'art' => 'MB9907ZT',
    'descr' => 'Сочетание изысканного дизайна, качественных материалов и продуманной функциональности.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB9907ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mp3619zt',
    'category' => 'beds',
    'name' => 'Кровать MP3619ZT',
    'art' => 'MP3619ZT',
    'descr' => 'Роскошная мягкая обивка и эффектное стёганое изголовье для разных стилей спальни.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MP3619ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mp3632zt',
    'category' => 'beds',
    'name' => 'Кровать MP3632ZT',
    'art' => 'MP3632ZT',
    'descr' => 'Идеальное сочетание изысканного дизайна, качественных материалов и продуманной функциональности.',
    'material' => 'Качественная обивка из премиальной кожи — мягкая, дышащая, износостойкая',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MP3632ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'beds-mb5192zt',
    'category' => 'beds',
    'name' => 'Кровать MB5192ZT',
    'art' => 'MB5192ZT',
    'descr' => 'Современный минимализм и продуманная функциональность.',
    'material' => 'Обивка из качественной ткани — мягкая и практичная',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/MB5192ZT.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-wmsf650',
    'category' => 'sofas',
    'name' => 'Диван WMSF650',
    'art' => 'WMSF650',
    'descr' => 'Современный комфорт и элегантный дизайн.',
    'material' => 'Высококачественная ткань, мягкие и упругие подушки',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/WMSF650.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-ysf7239',
    'category' => 'sofas',
    'name' => 'Модульный диван YSF-7239 «Паофу»',
    'art' => 'YSF-7239 «Паофу»',
    'descr' => 'Стиль, комфорт и свобода в каждом модуле.',
    'material' => 'Высококачественные материалы: качественная ткань букле + износостойкая экокожа',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF-7239_Паофу.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7029',
    'category' => 'sofas',
    'name' => 'Модульный диван CE-SF7029 «Пияфу»',
    'art' => 'CE-SF7029 «Пияфу»',
    'descr' => 'Изысканный дизайн и непревзойдённый комфорт.',
    'material' => 'Качественная ткань букле; обтекаемая изогнутая форма',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7029_Пияфу.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7013',
    'category' => 'sofas',
    'name' => 'Модульный диван CE-SF7013 «Имосен»',
    'art' => 'CE-SF7013 «Имосен»',
    'descr' => 'Комфорт, стиль и функциональность в каждой детали.',
    'material' => 'Качественная и приятная на ощупь ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7013_Имосен.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7021',
    'category' => 'sofas',
    'name' => 'Современный диван CE-SF7021 «МЕАНИ»',
    'art' => 'CE-SF7021 «МЕАНИ»',
    'descr' => 'Современный диван для комфортной жизни. Элегантные плавные линии и мягкие формы создают уютную атмосферу в вашем доме. Цвет: C195 коричневый.',
    'material' => 'Качественные материалы: букле высокого качества, износостойкая ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7021_МЕАНИ.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7030',
    'category' => 'sofas',
    'name' => 'Модульный диван CE-SF7030 «Макиато»',
    'art' => 'CE-SF7030 «Макиато»',
    'descr' => 'Уют, стиль и максимальный комфорт в каждой детали.',
    'material' => 'Качественная приятная на ощупь ткань',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7030_Макиато.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-ysf7241',
    'category' => 'sofas',
    'name' => 'Модульный диван YSF-7241 «Линшан»',
    'art' => 'YSF-7241 «Линшан»',
    'descr' => 'Современный дизайн и максимальный комфорт.',
    'material' => 'Качественная ткань, приятная на ощупь',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/YSF-7241_Линшан.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7012',
    'category' => 'sofas',
    'name' => 'Модульный диван CE-SF7012 «ДИЛАН»',
    'art' => 'CE-SF7012 «ДИЛАН»',
    'descr' => 'Современный стиль и комфорт в каждой детали.',
    'material' => 'Качественная ткань, приятная на ощупь',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7012_ДИЛАН.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'sofas-cesf7006',
    'category' => 'sofas',
    'name' => 'Модульный диван CE-SF7006 «БРЕЙЗЕР»',
    'art' => 'CE-SF7006 «БРЕЙЗЕР»',
    'descr' => 'Стиль, комфорт и функциональность в каждой детали.',
    'material' => 'Качественная ткань букле, приятная на ощупь',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/CE-SF7006_БРЕЙЗЕР.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'chairs-n130',
    'category' => 'chairs',
    'name' => 'Массажное кресло',
    'art' => 'N130',
    'descr' => 'Ваш личный центр расслабления и здоровья.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'chairs-n131',
    'category' => 'chairs',
    'name' => 'Массажное кресло',
    'art' => 'N131',
    'descr' => 'Расслабление и комфорт в каждом движении.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
  [
    'slug' => 'chairs-n132',
    'category' => 'chairs',
    'name' => 'Массажное кресло-реклайнер',
    'art' => 'N132',
    'descr' => 'Максимальное расслабление и забота о вашем теле.',
    'material' => 'Премиальные материалы',
    'sizes' => '',
    'color' => '',
    'packing' => '',
    'custom' => true,
    'objects' => ['hotel', 'apartment'],
    'image' => 'assets/uploads/Массажное_кресло-реклайнер_серое.jpeg',
    'subcategory' => '',
    'destination' => '',
  ],
];
